version: '3'

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - webserver

  apiserver:
    image: gcr.io/dockerregistry-195816/github-hcv57-coinrankchat-api:0986f04d47df7b891e02a60bf87cff9835f43230
    environment:
      ELASTIC_HOST: elasticsearch

  webserver:
    image: gcr.io/dockerregistry-195816/github-hcv57-coinrankchat-web:c0bf8295ba5a9e3413ccdb2dfa2971219f47f444
    environment:
      API_SERVER_HOST: "apiserver:8000"
      IMAGE_SERVER_URL: $IMAGE_SERVER_URL

  telegram:
    image: gcr.io/dockerregistry-195816/github-hcv57-coinrankchat-telegram:1981d6a6c4c9493fb4096489a534fb3e026f0fd4
    volumes:
      - ./coinrankchat.session:/usr/src/app/coinrankchat.session
    environment:
      ELASTIC_HOST: elasticsearch
      TELEGRAM_API_ID: $TELEGRAM_API_ID
      TELEGRAM_API_HASH: $TELEGRAM_API_HASH
      TELEGRAM_PHONE: $TELEGRAM_PHONE
      IMAGE_SERVER_URL: $IMAGE_SERVER_URL
      S3_KEY_ID: $S3_KEY_ID
      S3_SECRET: $S3_SECRET

  elasticsearch:
    image: elasticsearch
    volumes:
      - elastic-data-volume:/usr/share/elasticsearch/data

volumes:
  elastic-data-volume:
