version: '3'

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - webserver

  apiserver:
    image: gcr.io/dockerregistry-195816/github-hcv57-coinrankchat-api:8f759292793d4f9e2679596b8c4ae4556f80bec3
    environment:
      ELASTIC_HOST: elasticsearch

  webserver:
    image: gcr.io/dockerregistry-195816/github-hcv57-coinrankchat-web:710428efd2b34d66c6740c4658043cf173e1b34f
    environment:
      API_SERVER_HOST: "apiserver:8000"
      IMAGE_SERVER_URL: "https://coinrankchat.ams3.digitaloceanspaces.com"

  telegram:
    image: gcr.io/dockerregistry-195816/github-hcv57-coinrankchat-telegram:d2e5970589a73c0002c83b096e4a2aff72bbaa6e
    volumes:
      - ./coinrankchat.session:/usr/src/app/coinrankchat.session
    environment:
      ELASTIC_HOST: elasticsearch
      TELEGRAM_API_ID: $TELEGRAM_API_ID
      TELEGRAM_API_HASH: $TELEGRAM_API_HASH
      TELEGRAM_PHONE: $TELEGRAM_PHONE

  elasticsearch:
    image: elasticsearch
    volumes:
      - elastic-data-volume:/usr/share/elasticsearch/data

volumes:
  elastic-data-volume:
